import { Member } from '@digitaldefiance/ecies-lib';
import { ValidationChain } from 'express-validator';
import { RequestCostAccumulator } from './joule/requestCostAccumulator';
import { ValidatedBody } from './shared-types';

declare module 'express-serve-static-core' {
  interface Request {
    brightchainUser?: Member;
    validatedBody?: ValidatedBody<string>;
    validate?: {
      body: (field: string) => ValidationChain;
      param: (field: string) => ValidationChain;
      query: (field: string) => ValidationChain;
      header: (field: string) => ValidationChain;
      cookie: (field: string) => ValidationChain;
    };
    /**
     * Unique request ID (UUID v4) generated by requestIdMiddleware.
     * Used for request tracing and included in error responses.
     * @requirements 9.5
     */
    requestId?: string;
    /**
     * Per-request Joule resource-cost accumulator, attached by CaptureMiddleware.
     * Route handlers accrue resource consumption via `req.joule.add(cls, units)`.
     * The middleware emits one Resource_Event per non-zero class on response close.
     *
     * @requirements joule-resource-credits 2.1, 2.2
     */
    joule?: RequestCostAccumulator;
  }
}

declare global {
  namespace Express {
    interface Request {
      brightchainUser?: Member;
      validatedBody?: ValidatedBody<string>;
      validate?: {
        body: (field: string) => ValidationChain;
        param: (field: string) => ValidationChain;
        query: (field: string) => ValidationChain;
        header: (field: string) => ValidationChain;
        cookie: (field: string) => ValidationChain;
      };
      /**
       * Unique request ID (UUID v4) generated by requestIdMiddleware.
       * Used for request tracing and included in error responses.
       * @requirements 9.5
       */
      requestId?: string;
      /**
       * Per-request Joule resource-cost accumulator, attached by CaptureMiddleware.
       * Route handlers accrue resource consumption via `req.joule.add(cls, units)`.
       * The middleware emits one Resource_Event per non-zero class on response close.
       *
       * @requirements joule-resource-credits 2.1, 2.2
       */
      joule?: RequestCostAccumulator;
    }
  }
}
