compressionLevel: mixed
enableGlobalCache: false
enableScripts: true
globalFolder: ./.yarn/global
nodeLinker: pnpm

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  awesome.me:
    npmAlwaysAuth: true # Changed to true since Verdaccio is locked down
    npmRegistryServer: "https://verdaccio-registry.nicefield-46a11a16.westus2.azurecontainerapps.io"
    npmAuthToken: "${BRIGHTCHAIN_REGISTRY_TOKEN}"
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://verdaccio-registry.nicefield-46a11a16.westus2.azurecontainerapps.io"
    npmAuthToken: "${BRIGHTCHAIN_REGISTRY_TOKEN}"

unsafeHttpWhitelist:
  - localhost