compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

globalFolder: ./.yarn/global

nodeLinker: pnpm

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"

unsafeHttpWhitelist:
  - localhost
