compressionLevel: mixed
enableGlobalCache: false
enableScripts: true
nodeLinker: pnpm
globalFolder: ./.yarn/global

npmRegistryServer: "https://registry.npmjs.org"

unsafeHttpWhitelist:
  - "localhost"

npmScopes:
  "awesome.me":
    npmAlwaysAuth: false
    npmRegistryServer: "http://localhost:4873/"

packageExtensions: {}
