export enum CblErrorType {
  CblRequired = 'CblRequired',
  WhitenedBlockFunctionRequired = 'WhitenedBlockFunctionRequired',
  FailedToLoadBlock = 'FailedToLoadBlock',
  ExpectedEncryptedDataBlock = 'ExpectedEncryptedDataBlock',
  ExpectedOwnedDataBlock = 'ExpectedOwnedDataBlock',
  InvalidStructure = 'InvalidStructure',
  CreatorUndefined = 'CreatorUndefined',
  BlockNotReadable = 'BlockNotReadable',
  CreatorRequiredForSignature = 'CreatorRequiredForSignature',
  FileNameRequired = 'FileNameRequired',
  FileNameEmpty = 'FileNameEmpty',
  FileNameWhitespace = 'FileNameWhitespace',
  FileNameInvalidChar = 'FileNameInvalidChar',
  FileNameControlChars = 'FileNameControlChars',
  FileNamePathTraversal = 'FileNamePathTraversal',
  MimeTypeRequired = 'MimeTypeRequired',
  MimeTypeEmpty = 'MimeTypeEmpty',
  MimeTypeWhitespace = 'MimeTypeWhitespace',
  MimeTypeLowercase = 'MimeTypeLowercase',
  MimeTypeInvalidFormat = 'MimeTypeInvalidFormat',
  InvalidBlockSize = 'InvalidBlockSize',
  InvalidSignature = 'InvalidSignature',
  MetadataSizeExceeded = 'MetadataSizeExceeded',
  MetadataSizeNegative = 'MetadataSizeNegative',
  InvalidMetadataBuffer = 'InvalidMetadataBuffer',
  NotExtendedCbl = 'NotExtendedCbl',
}
