export enum EciesErrorType {
  InvalidIVLength = 'InvalidIVLength',
  InvalidAuthTagLength = 'InvalidAuthTagLength',
  InvalidHeaderLength = 'InvalidHeaderLength',
  InvalidDataLength = 'InvalidDataLength',
  InvalidEncryptedDataLength = 'InvalidEncryptedDataLength',
  InvalidMnemonic = 'InvalidMnemonic',
  MessageLengthMismatch = 'MessageLengthMismatch',
  InvalidEncryptedKeyLength = 'InvalidEncryptedKeyLength',
  InvalidEphemeralPublicKey = 'InvalidEphemeralPublicKey',
  RecipientNotFound = 'RecipientNotFound',
  InvalidSignature = 'InvalidSignature',
  InvalidSenderPublicKey = 'InvalidSenderPublicKey',
  TooManyRecipients = 'TooManyRecipients',
  PrivateKeyNotLoaded = 'PrivateKeyNotLoaded',
  RecipientKeyCountMismatch = 'RecipientKeyCountMismatch',
  InvalidRecipientCount = 'InvalidRecipientCount',
  FileSizeTooLarge = 'FileSizeTooLarge',
}
