export enum ExtendedCblErrorType {
  CreatorUndefined = 'CreatorUndefined',
  BlockNotReadable = 'BlockNotReadable',
  CreatorRequiredForSignature = 'CreatorRequiredForSignature',
  FileNameRequired = 'FileNameRequired',
  FileNameEmpty = 'FileNameEmpty',
  FileNameWhitespace = 'FileNameWhitespace',
  FileNameInvalidChar = 'FileNameInvalidChar',
  FileNameControlChars = 'FileNameControlChars',
  FileNamePathTraversal = 'FileNamePathTraversal',
  FileNameTooLong = 'FileNameTooLong',
  MimeTypeRequired = 'MimeTypeRequired',
  MimeTypeEmpty = 'MimeTypeEmpty',
  MimeTypeWhitespace = 'MimeTypeWhitespace',
  MimeTypeLowercase = 'MimeTypeLowercase',
  MimeTypeInvalidFormat = 'MimeTypeInvalidFormat',
  MimeTypeTooLong = 'MimeTypeTooLong',
  InvalidBlockSize = 'InvalidBlockSize',
  MetadataSizeExceeded = 'MetadataSizeExceeded',
  MetadataSizeNegative = 'MetadataSizeNegative',
  InvalidMetadataBuffer = 'InvalidMetadataBuffer',
  InvalidStructure = 'InvalidStructure',
  CreationFailed = 'CreationFailed',
  InsufficientCapacity = 'InsufficientCapacity',
  NotExtendedCbl = 'NotExtendedCbl',
}
