export enum FecErrorType {
  DataRequired = 'DataRequired',
  InvalidShardCounts = 'InvalidShardCounts',
  InvalidShardsAvailableArray = 'InvalidShardsAvailableArray',
  InputBlockRequired = 'InputBlockRequired',
  ParityBlockCountMustBePositive = 'ParityBlockCountMustBePositive',
  InputDataMustBeBuffer = 'InputDataMustBeBuffer',
  DamagedBlockRequired = 'DamagedBlockRequired',
  ParityBlocksRequired = 'ParityBlocksRequired',
  BlockSizeMismatch = 'BlockSizeMismatch',
  DamagedBlockDataMustBeBuffer = 'DamagedBlockDataMustBeBuffer',
  ParityBlockDataMustBeBuffer = 'ParityBlockDataMustBeBuffer',
  InvalidDataLength = 'InvalidDataLength',
  ShardSizeExceedsMaximum = 'ShardSizeExceedsMaximum',
  NotEnoughShardsAvailable = 'NotEnoughShardsAvailable',
  InvalidParityBlockSize = 'InvalidParityBlockSize',
  InvalidRecoveredBlockSize = 'InvalidRecoveredBlockSize',
  FecEncodingFailed = 'FecEncodingFailed',
  FecDecodingFailed = 'FecDecodingFailed',
}
