export enum OperationType {
  // Block Operations
  BLOCK_STORE = 'BLOCK_STORE',
  BLOCK_RETRIEVE = 'BLOCK_RETRIEVE',
  BLOCK_DELETE = 'BLOCK_DELETE',
  BLOCK_VERIFY = 'BLOCK_VERIFY',

  // CBL Operations
  CBL_CREATE = 'CBL_CREATE',
  CBL_RETRIEVE = 'CBL_RETRIEVE',
  CBL_UPDATE = 'CBL_UPDATE',

  // Whitening Operations
  WHITEN_BLOCK = 'WHITEN_BLOCK',
  UNWHITEN_BLOCK = 'UNWHITEN_BLOCK',

  // Encryption Operations
  ENCRYPT_BLOCK = 'ENCRYPT_BLOCK',
  DECRYPT_BLOCK = 'DECRYPT_BLOCK',
  ENCRYPT_MULTI = 'ENCRYPT_MULTI',

  // Quorum Operations
  QUORUM_SEAL = 'QUORUM_SEAL',
  QUORUM_UNSEAL = 'QUORUM_UNSEAL',
  QUORUM_VOTE = 'QUORUM_VOTE',

  // Messaging Operations
  MESSAGE_SEND = 'MESSAGE_SEND',
  MESSAGE_FORWARD = 'MESSAGE_FORWARD',
  MESSAGE_BROADCAST = 'MESSAGE_BROADCAST',

  // Reputation Operations
  RATE_CONTENT = 'RATE_CONTENT',
  RATE_MEMBER = 'RATE_MEMBER',

  // Network Operations
  PEER_DISCOVERY = 'PEER_DISCOVERY',
  BLOCK_REPLICATION = 'BLOCK_REPLICATION',
  GOSSIP_PROPAGATION = 'GOSSIP_PROPAGATION',

  // Energy Operations
  ENERGY_TRANSFER = 'ENERGY_TRANSFER',
  ENERGY_GRANT = 'ENERGY_GRANT',
}
