export enum StoreErrorType {
  StorePathRequired = 'StorePathRequired',
  StorePathNotFound = 'StorePathNotFound',
  KeyNotFound = 'KeyNotFound',
  BlockSizeMismatch = 'BlockSizeMismatch',
  BlockPathAlreadyExists = 'BlockPathAlreadyExists',
  BlockFileSizeMismatch = 'BlockFileSizeMismatch',
  BlockValidationFailed = 'BlockValidationFailed',
  NoBlocksProvided = 'NoBlocksProvided',
  InvalidBlockMetadata = 'InvalidBlockMetadata',
  BlockSizeRequired = 'BlockSizeRequired',
  BlockIdRequired = 'BlockIdRequired',
  InvalidBlockIdTooShort = 'InvalidBlockIdTooShort',
  CannotStoreEphemeralData = 'CannotStoreEphemeralData',
  BlockIdMismatch = 'BlockIdMismatch',
  BlockDirectoryCreationFailed = 'BlockDirectoryCreationFailed',
  BlockDeletionFailed = 'BlockDeletionFailed',
}
