export enum StringNames {
  ChangePassword_Success = 'changePassword_success',
  Common_ChangePassword = 'common_changePassword',
  Common_Dashboard = 'common_dashboard',
  Common_Logo = 'common_logo',
  Common_Site = 'common_site',
  Common_Unauthorized = 'common_unauthorized',
  Error_InvalidLanguageCode = 'error_invalidLanguageCode',
  Error_TokenExpired = 'error_tokenExpired',
  Error_TokenInvalid = 'error_tokenInvalid',
  Error_UnexpectedError = 'error_unexpectedError',
  Error_UserNotFound = 'error_userNotFound',
  Error_ValidationError = 'error_validationError',
  ForgotPassword_Title = 'forgotPassword_title',
  LanguageUpdate_Success = 'languageUpdate_success',
  Login_LoginButton = 'login_loginButton',
  LogoutButton = 'logoutButton',
  Register_Button = 'register_button',
  Register_Error = 'register_error',
  Register_Success = 'register_success',
  Validation_InvalidLanguage = 'validation_invalidLanguage',
}
