// Existing base interfaces
export type * from './acl';
export type * from './canary';
export type * from './chirp';
export type * from './file';
export type * from './folder';
export type * from './protocol';
export type * from './user';

// File platform base interfaces
export type * from './acl-document';
export type * from './acl-entry';
export type * from './approval-request';
export type * from './audit-entry';
export type * from './canary-binding';
export type * from './certificate-of-destruction';
export type * from './destruction-certificate';
export type * from './file-access-ledger-entry';
export type * from './file-metadata';
export type * from './file-non-access-proof';
export type * from './file-popularity-record';
export type * from './file-version';
export type * from './folder-metadata';
export type * from './key-wrapping-entry';
export type * from './notification';
export type * from './permission-set';
export type * from './recipient-list';
export type * from './resolved-acl';
export type * from './share-link';
export type * from './storage-quota';
export type * from './upload-session';
export type * from './vault-access-audit-entry';
export type * from './vault-container';
