/**
 * BrightHub Social Network Database Schemas
 *
 * This module exports all collection schemas for the BrightHub social network.
 */

// Posts
export {
  POSTS_COLLECTION,
  POSTS_SCHEMA,
  POST_REPORTS_COLLECTION,
  POST_REPORTS_SCHEMA,
  POST_REPORT_STATUS_VALUES,
  POST_TYPE_VALUES,
} from './posts.schema';

// Social Interactions (Follows, Likes, Reposts)
export {
  FOLLOWS_COLLECTION,
  FOLLOWS_SCHEMA,
  LIKES_COLLECTION,
  LIKES_SCHEMA,
  REPOSTS_COLLECTION,
  REPOSTS_SCHEMA,
  VOTES_COLLECTION,
  VOTES_SCHEMA,
  VOTE_TYPE_VALUES,
} from './interactions.schema';

// Notifications
export {
  NOTIFICATIONS_COLLECTION,
  NOTIFICATIONS_SCHEMA,
  NOTIFICATION_CATEGORY_VALUES,
  NOTIFICATION_TYPE_VALUES,
} from './notifications.schema';

// Notification Settings (Preferences and Groups)
export {
  NOTIFICATION_CHANNEL_VALUES,
  NOTIFICATION_GROUPS_COLLECTION,
  NOTIFICATION_GROUPS_SCHEMA,
  NOTIFICATION_PREFERENCES_COLLECTION,
  NOTIFICATION_PREFERENCES_SCHEMA,
} from './notification-settings.schema';

// Connection Management
export {
  // Connection Categories
  CONNECTION_CATEGORIES_COLLECTION,
  CONNECTION_CATEGORIES_SCHEMA,
  // Connection Category Assignments
  CONNECTION_CATEGORY_ASSIGNMENTS_COLLECTION,
  CONNECTION_CATEGORY_ASSIGNMENTS_SCHEMA,
  // Connection Interactions
  CONNECTION_INTERACTIONS_COLLECTION,
  CONNECTION_INTERACTIONS_SCHEMA,
  // Connection Lists
  CONNECTION_LISTS_COLLECTION,
  CONNECTION_LISTS_SCHEMA,
  CONNECTION_LIST_FOLLOWERS_COLLECTION,
  CONNECTION_LIST_FOLLOWERS_SCHEMA,
  CONNECTION_LIST_MEMBERS_COLLECTION,
  CONNECTION_LIST_MEMBERS_SCHEMA,
  // Connection Metadata
  CONNECTION_METADATA_COLLECTION,
  CONNECTION_METADATA_SCHEMA,
  // Connection Notes
  CONNECTION_NOTES_COLLECTION,
  CONNECTION_NOTES_SCHEMA,
  CONNECTION_STRENGTH_VALUES,
  CONNECTION_VISIBILITY_VALUES,
  // Follow Requests
  FOLLOW_REQUESTS_COLLECTION,
  FOLLOW_REQUESTS_SCHEMA,
  FOLLOW_REQUEST_STATUS_VALUES,
  // Hubs
  HUBS_COLLECTION,
  HUBS_SCHEMA,
  HUB_BANNED_USERS_COLLECTION,
  HUB_BANNED_USERS_SCHEMA,
  HUB_MEMBERS_COLLECTION,
  HUB_MEMBERS_SCHEMA,
  MUTE_DURATION_VALUES,
  // Temporary Mutes
  TEMPORARY_MUTES_COLLECTION,
  TEMPORARY_MUTES_SCHEMA,
} from './connections.schema';

// User Profiles, Blocks, and Mutes
export {
  APPROVE_FOLLOWERS_MODE_VALUES,
  BLOCKS_COLLECTION,
  BLOCKS_SCHEMA,
  MUTES_COLLECTION,
  MUTES_SCHEMA,
  USER_PROFILES_COLLECTION,
  USER_PROFILES_SCHEMA,
} from './users.schema';

// Messaging
export {
  // Archived Conversations
  ARCHIVED_CONVERSATIONS_COLLECTION,
  ARCHIVED_CONVERSATIONS_SCHEMA,
  // Conversations
  CONVERSATIONS_COLLECTION,
  CONVERSATIONS_SCHEMA,
  // Conversation Participants
  CONVERSATION_PARTICIPANTS_COLLECTION,
  CONVERSATION_PARTICIPANTS_SCHEMA,
  CONVERSATION_TYPE_VALUES,
  GROUP_PARTICIPANT_ROLE_VALUES,
  // Messages
  MESSAGES_COLLECTION,
  MESSAGES_SCHEMA,
  // Message Reactions
  MESSAGE_REACTIONS_COLLECTION,
  MESSAGE_REACTIONS_SCHEMA,
  // Message Reports
  MESSAGE_REPORTS_COLLECTION,
  MESSAGE_REPORTS_SCHEMA,
  // Message Requests
  MESSAGE_REQUESTS_COLLECTION,
  MESSAGE_REQUESTS_SCHEMA,
  MESSAGE_REQUEST_STATUS_VALUES,
  // Muted Conversations
  MUTED_CONVERSATIONS_COLLECTION,
  MUTED_CONVERSATIONS_SCHEMA,
  // Pinned Conversations
  PINNED_CONVERSATIONS_COLLECTION,
  PINNED_CONVERSATIONS_SCHEMA,
  // Read Receipts
  READ_RECEIPTS_COLLECTION,
  READ_RECEIPTS_SCHEMA,
  REPORT_STATUS_VALUES,
  REPORT_TYPE_VALUES,
} from './messaging.schema';

// Hub Reputation
export {
  HUB_REPUTATION_COLLECTION,
  HUB_REPUTATION_SCHEMA,
} from './reputation.schema';
