export enum BrightNexusStrings {
  Page_Title = 'Page_Title',
  Page_Subtitle = 'Page_Subtitle',
  Form_IpAddress = 'Form_IpAddress',
  Form_Latitude = 'Form_Latitude',
  Form_Longitude = 'Form_Longitude',
  Form_Altitude = 'Form_Altitude',
  Form_Epoch = 'Form_Epoch',
  Form_HeisenbergMode = 'Form_HeisenbergMode',
  Form_InjectedDelayMd = 'Form_InjectedDelayMd',
  Form_FuzzRadiusKm = 'Form_FuzzRadiusKm',
  Form_Publish = 'Form_Publish',
  Form_Refresh = 'Form_Refresh',
  List_Empty = 'List_Empty',
  List_Revoke = 'List_Revoke',
  DnsTxt_Label = 'DnsTxt_Label',
  Error_PublishFailed = 'Error_PublishFailed',
}
