/**
 * Common types used throughout brightchain-db.
 *
 * All types are now defined in @brightchain/brightchain-lib and re-exported here
 * for backward compatibility. ClientSession is a type alias for IClientSession.
 */
export {
  type AggregationStage,
  type BsonDocument,
  type BulkWriteOperation,
  type BulkWriteOptions,
  type BulkWriteResult,
  type ChangeEvent,
  type ChangeEventType,
  type ChangeListener,
  type ClientSession,
  type CollectionOptions,
  type CollectionSchema,
  type CollectionSchemaFieldType,
  type CursorSession,
  type DeleteResult,
  type DocumentId,
  type FieldSchema,
  type FilterOperator,
  type FilterQuery,
  type FindOptions,
  type IClientSession,
  type IndexOptions,
  type IndexSpec,
  type InsertManyResult,
  type InsertOneResult,
  type LogicalOperators,
  type ProjectionSpec,
  type ReadPreference,
  type ReplaceResult,
  type SortSpec,
  type TextIndexOptions,
  type UpdateOperators,
  type UpdateOptions,
  type UpdateQuery,
  type UpdateResult,
  type ValidationFieldError,
  type WriteConcern,
  type WriteOptions,
} from '@brightchain/brightchain-lib';
