import { PlatformID } from '@digitaldefiance/ecies-lib';
import type { BurnbagStorageTier } from '../../joule/burnbagDurability';

/**
 * Parameters for creating a new upload session.
 *
 * When BURNBAG_JOULE_ENABLED=true, `durabilityTier` and `durationDays` are
 * effectively required (the service layer validates this at runtime).
 */
export interface ICreateUploadSessionParams<TID extends PlatformID> {
  userId: TID;
  fileName: string;
  mimeType: string;
  totalSizeBytes: number;
  targetFolderId: TID;
  vaultContainerId: TID;
  /**
   * User-selected storage durability tier.
   * Required when BURNBAG_JOULE_ENABLED=true; ignored otherwise.
   */
  durabilityTier?: BurnbagStorageTier;
  /**
   * Committed storage duration in days (≥ 1).
   * Required when BURNBAG_JOULE_ENABLED=true; ignored otherwise.
   */
  durationDays?: number;

  // ── Client-side E2EE upload ─────────────────────────────────────────────
  /**
   * Base64-encoded ECIES-wrapped symmetric key generated by the client.
   * When all three `preEncrypted*` fields are present, finalize() skips
   * server-side encryption and stores the client-provided key and IV.
   */
  preEncryptedWrappedKeyB64?: string;
  /** Base64-encoded 12-byte AES-GCM IV used by the client. */
  preEncryptedIvB64?: string;
  /** Base64-encoded 16-byte AES-GCM auth tag from the client. */
  preEncryptedAuthTagB64?: string;
}

/**
 * Receipt returned after a chunk is received.
 */
export interface IChunkReceipt {
  chunkIndex: number;
  received: boolean;
  /** Progress as a number between 0 and 1 */
  progress: number;
}

/**
 * Status of an upload session (for resume).
 */
export interface IUploadSessionStatus {
  sessionId: string;
  receivedChunks: number[];
  totalChunks: number;
  expired: boolean;
}

/**
 * Parameters for creating a new-version upload session for an existing file.
 */
export interface ICreateNewVersionSessionParams<TID extends PlatformID> {
  userId: TID;
  /** The existing file to create a new version of */
  fileId: TID;
  fileName: string;
  mimeType: string;
  totalSizeBytes: number;
}
