import { Pbkdf2Profiles } from '../pbkdf2Profiles';
import { IBackupCodeConstants } from './backupCodeConsts';
import { ICBLConsts } from './cblConsts';
import { IChecksumConsts } from './checksumConsts';
import { IECIESConsts } from './eciesConsts';
import { IEncryptionConsts } from './encryptionConsts';
import { IFECConsts } from './fecConsts';
import { IJwtConsts } from './jwtConsts';
import { IKeyringConsts } from './keyringConsts';
import { IPBkdf2Consts } from './pbkdf2Consts';
import { ISealingConsts } from './sealingConsts';
import { ISiteConsts } from './siteConsts';
import { ITupleConsts } from './tupleConsts';
import { IVotingConsts } from './votingConsts';

export interface IConstants {
  PBKDF2_PROFILES: Pbkdf2Profiles;
  BACKUP_CODES: IBackupCodeConstants;
  CBL: ICBLConsts;
  OFFS_CACHE_PERCENTAGE: number;
  ECIES: IECIESConsts;
  FEC: IFECConsts;
  CHECKSUM: IChecksumConsts;
  ENCRYPTION: IEncryptionConsts;
  TUPLE: ITupleConsts;
  VOTING: IVotingConsts;
  KEYRING: IKeyringConsts;
  SEALING: ISealingConsts;
  PBKDF2: IPBkdf2Consts;
  JWT: IJwtConsts;
  SITE: ISiteConsts;
  ECIES_OVERHEAD_LENGTH: number;
  ECIES_MULTIPLE_MESSAGE_OVERHEAD_LENGTH: number;
  KEYRING_ALGORITHM_CONFIGURATION: string;
  SYMMETRIC_ALGORITHM_CONFIGURATION: string;
  UINT8_SIZE: number;
  UINT16_SIZE: number;
  UINT16_MAX: number;
  UINT32_SIZE: number;
  UINT32_MAX: number;
  UINT64_SIZE: number;
  UINT64_MAX: bigint;
  HEX_RADIX: number;
  GUID_SIZE: number;
}
