import { ECIES } from '@digitaldefiance/ecies-lib';

export const BRIGHTCHAIN_ECIES = {
  ...ECIES,
  PUBLIC_KEY_MAGIC: 0x04,
  OVERHEAD_SIZE: ECIES.PUBLIC_KEY_LENGTH + ECIES.IV_SIZE + ECIES.AUTH_TAG_SIZE,
  SIGNATURE_LENGTH: 64,
  IV_LENGTH: ECIES.IV_SIZE,
  AUTH_TAG_LENGTH: ECIES.AUTH_TAG_SIZE,
  SYMMETRIC: {
    ...ECIES.SYMMETRIC,
    KEY_LENGTH: 32,
  },
  MULTIPLE: {
    ...ECIES.MULTIPLE,
    ENCRYPTED_KEY_SIZE: 65,
    ENCRYPTED_MESSAGE_OVERHEAD_SIZE: 28,
    FIXED_OVERHEAD_SIZE: 1,
  },
};
