import {
  getCharacterCount as getCharCount,
  IFormatOptions,
  IFormattedContent,
  ITextFormatter,
  IValidationResult,
  parsePostContent,
} from '@brightchain/brighthub-lib';
import sanitizeHtml from 'sanitize-html';

/**
 * Default maximum character count for posts
 */
export const DEFAULT_POST_MAX_CHARACTERS = 280;

/**
 * Default maximum character count for messages
 */
export const DEFAULT_MESSAGE_MAX_CHARACTERS = 2000;

/**
 * Maximum mentions allowed per post
 */
export const MAX_MENTIONS_PER_POST = 10;

/**
 * Maximum hashtags allowed per post
 */
export const MAX_HASHTAGS_PER_POST = 10;

/**
 * Regex pattern for extracting @mentions
 * Matches @username where username is alphanumeric with underscores, 1-30 chars
 */
const MENTION_REGEX =
  /(?:^|[^@\w])@([a-zA-Z_][a-zA-Z0-9_]{0,29})(?=\s|$|[^\w])/g;

/**
 * Regex pattern for extracting #hashtags
 * Matches #hashtag where hashtag is alphanumeric with underscores, 1-50 chars
 */
const HASHTAG_REGEX =
  /(?:^|[^#\w])#([a-zA-Z_][a-zA-Z0-9_]{0,49})(?=\s|$|[^\w])/g;

/**
 * Sanitize-html configuration for XSS prevention
 * Allows safe HTML tags that may be generated by markdown parsing
 */
const SANITIZE_CONFIG: sanitizeHtml.IOptions = {
  allowedTags: [
    'p',
    'br',
    'b',
    'i',
    'em',
    'strong',
    'a',
    'ul',
    'ol',
    'li',
    'code',
    'pre',
    'blockquote',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'table',
    'thead',
    'tbody',
    'tr',
    'th',
    'td',
    'del',
    's',
    'mark',
    'sup',
    'sub',
    'span',
    'div',
    'section',
    'input', // For task lists
  ],
  allowedAttributes: {
    a: ['href', 'title', 'target', 'rel'],
    img: ['src', 'alt', 'title', 'width', 'height'],
    input: ['type', 'checked', 'disabled', 'class'],
    '*': ['class', 'id', 'style'],
  },
  allowedStyles: {
    '*': {
      color: [
        /^#[0-9A-Fa-f]{3,6}$/,
        /^[a-zA-Z]+$/,
        /^rgb\(\d+,\s*\d+,\s*\d+\)$/,
        /^rgba\(\d+,\s*\d+,\s*\d+,\s*[\d.]+\)$/,
      ],
      'font-size': [/^\d+(?:px|em|rem|%)$/],
      'font-weight': [/^(?:normal|bold|\d{3})$/],
      'text-align': [/^(?:left|right|center|justify)$/],
      display: [/^inline-block$/],
    },
  },
  allowedSchemes: ['http', 'https', 'mailto'],
  allowedSchemesByTag: {
    a: ['http', 'https', 'mailto'],
  },
  transformTags: {
    a: (tagName, attribs) => {
      // Add rel="noopener noreferrer" and target="_blank" to external links
      const href = attribs['href'] || '';
      if (href.startsWith('http://') || href.startsWith('https://')) {
        return {
          tagName,
          attribs: {
            ...attribs,
            target: '_blank',
            rel: 'noopener noreferrer',
          },
        };
      }
      return { tagName, attribs };
    },
  },
};

/**
 * Strict sanitize config that strips all HTML (for input sanitization)
 */
const STRICT_SANITIZE_CONFIG: sanitizeHtml.IOptions = {
  allowedTags: [],
  allowedAttributes: {},
};

/**
 * Text_Formatter service implementation
 * Provides unified API for formatting post content with markdown, emojis, and FontAwesome icons
 */
export class TextFormatter implements ITextFormatter {
  /**
   * Format content with markdown, emojis, and FontAwesome icons
   * Also extracts mentions and hashtags
   */
  format(content: string, options: IFormatOptions = {}): IFormattedContent {
    const { isBlogPost = false, docId, currentUrl } = options;

    // Extract mentions and hashtags before formatting (from raw content)
    const mentions = this.extractMentions(content);
    const hashtags = this.extractHashtags(content);

    // Get character count from raw content
    const characterCount = this.getCharacterCount(content, isBlogPost);

    // Format the content using existing brighthub-lib function
    const formatted = parsePostContent(content, isBlogPost, docId, currentUrl);

    // Sanitize the formatted output for XSS prevention
    const sanitizedFormatted = this.sanitizeOutput(formatted);

    return {
      raw: content,
      formatted: sanitizedFormatted,
      mentions,
      hashtags,
      characterCount,
    };
  }

  /**
   * Extract @mentions from content
   * Returns unique usernames without the @ prefix
   */
  extractMentions(content: string): string[] {
    const mentions: Set<string> = new Set();
    let match: RegExpExecArray | null;

    // Reset regex lastIndex
    MENTION_REGEX.lastIndex = 0;

    while ((match = MENTION_REGEX.exec(content)) !== null) {
      const username = match[1].toLowerCase();
      mentions.add(username);
    }

    return Array.from(mentions);
  }

  /**
   * Extract #hashtags from content
   * Returns unique hashtags without the # prefix
   */
  extractHashtags(content: string): string[] {
    const hashtags: Set<string> = new Set();
    let match: RegExpExecArray | null;

    // Reset regex lastIndex
    HASHTAG_REGEX.lastIndex = 0;

    while ((match = HASHTAG_REGEX.exec(content)) !== null) {
      const hashtag = match[1].toLowerCase();
      hashtags.add(hashtag);
    }

    return Array.from(hashtags);
  }

  /**
   * Sanitize input content to prevent XSS attacks
   * Strips all HTML tags from input
   */
  sanitize(content: string): string {
    return sanitizeHtml(content, STRICT_SANITIZE_CONFIG);
  }

  /**
   * Sanitize formatted output while preserving safe HTML
   */
  private sanitizeOutput(content: string): string {
    return sanitizeHtml(content, SANITIZE_CONFIG);
  }

  /**
   * Get character count using smart counting rules
   */
  getCharacterCount(content: string, isBlogPost = false): number {
    return getCharCount(content, isBlogPost);
  }

  /**
   * Validate content against formatting rules
   */
  validate(content: string, options: IFormatOptions = {}): IValidationResult {
    const errors: string[] = [];
    const { isBlogPost = false, maxCharacters } = options;

    // Check for empty content
    if (!content || content.trim().length === 0) {
      errors.push('Content cannot be empty');
      return { isValid: false, errors };
    }

    // Check character count
    const charCount = this.getCharacterCount(content, isBlogPost);
    const maxChars = maxCharacters ?? DEFAULT_POST_MAX_CHARACTERS;

    if (charCount > maxChars) {
      errors.push(
        `Content exceeds maximum character limit of ${maxChars} (current: ${charCount})`,
      );
    }

    // Check mention count
    const mentions = this.extractMentions(content);
    if (mentions.length > MAX_MENTIONS_PER_POST) {
      errors.push(
        `Too many mentions (maximum: ${MAX_MENTIONS_PER_POST}, found: ${mentions.length})`,
      );
    }

    // Check hashtag count
    const hashtags = this.extractHashtags(content);
    if (hashtags.length > MAX_HASHTAGS_PER_POST) {
      errors.push(
        `Too many hashtags (maximum: ${MAX_HASHTAGS_PER_POST}, found: ${hashtags.length})`,
      );
    }

    return {
      isValid: errors.length === 0,
      errors,
    };
  }
}

/**
 * Singleton instance of TextFormatter
 */
let textFormatterInstance: TextFormatter | null = null;

/**
 * Get the singleton TextFormatter instance
 */
export function getTextFormatter(): TextFormatter {
  if (!textFormatterInstance) {
    textFormatterInstance = new TextFormatter();
  }
  return textFormatterInstance;
}

/**
 * Create a new TextFormatter instance
 */
export function createTextFormatter(): TextFormatter {
  return new TextFormatter();
}
