import { blake3 } from '@noble/hashes/blake3';

import { decodeMeteringRecord } from './record.js';

// ── RFC-9162 domain-separation prefixes ───────────────────────────────────────
// Using 0x00 for leaves and 0x01 for internal nodes prevents second-preimage
// attacks where an internal node hash could be mistaken for a valid leaf.
const LEAF_PREFIX = 0x00;
const INTERNAL_PREFIX = 0x01;

// ── Hash primitives ───────────────────────────────────────────────────────────

/**
 * Compute a Merkle leaf hash: BLAKE3(0x00 || encodedRecord).
 *
 * The 0x00 domain prefix provides RFC-9162 §2.1 second-preimage resistance.
 */
export function merkleLeafHash(encodedRecord: Uint8Array): Uint8Array {
  const msg = new Uint8Array(1 + encodedRecord.length);
  msg[0] = LEAF_PREFIX;
  msg.set(encodedRecord, 1);
  return blake3(msg);
}

/**
 * Compute a Merkle internal node hash: BLAKE3(0x01 || left || right).
 *
 * Both left and right must be 32-byte hashes.
 */
export function merkleInternalHash(
  left: Uint8Array,
  right: Uint8Array,
): Uint8Array {
  const msg = new Uint8Array(65); // 1 + 32 + 32
  msg[0] = INTERNAL_PREFIX;
  msg.set(left, 1);
  msg.set(right, 33);
  return blake3(msg);
}

// ── Tree construction ─────────────────────────────────────────────────────────

/**
 * Returns the largest power of 2 strictly less than n.
 *
 * Used to determine the RFC-9162 split point k when constructing or
 * traversing a subtree of size n.
 *
 * @throws {RangeError} if n < 2
 */
export function largestPowerOf2Below(n: number): number {
  if (n < 2) {
    throw new RangeError(`largestPowerOf2Below requires n >= 2, got ${n}`);
  }
  let k = 1;
  while (k < n) k <<= 1;
  return k >>> 1;
}

/**
 * Compute the Merkle root for an ordered list of pre-computed leaf hashes.
 *
 * Follows RFC-9162 §2.1 recursive construction:
 *   MTH([])    = BLAKE3([])             (empty tree)
 *   MTH([h])   = h                      (single leaf)
 *   MTH(H[n])  = BLAKE3(0x01 || MTH(H[0:k]) || MTH(H[k:n]))
 *                where k = largestPowerOf2Below(n)
 *
 * @param leaves  Array of 32-byte leaf hashes (already passed through
 *                {@link merkleLeafHash}).
 */
export function merkleRootFromLeaves(leaves: Uint8Array[]): Uint8Array {
  if (leaves.length === 0) {
    return blake3(new Uint8Array(0));
  }
  if (leaves.length === 1) {
    return leaves[0];
  }
  const k = largestPowerOf2Below(leaves.length);
  const leftRoot = merkleRootFromLeaves(leaves.slice(0, k));
  const rightRoot = merkleRootFromLeaves(leaves.slice(k));
  return merkleInternalHash(leftRoot, rightRoot);
}

// ── Inclusion proof ───────────────────────────────────────────────────────────

export interface InclusionProof {
  /** 0-based index of the leaf within the batch window. */
  leafIndex: number;
  /** 32-byte leaf hash = BLAKE3(0x00 || encodedRecord). */
  leafHash: Uint8Array;
  /**
   * Merkle audit path — sibling hashes from leaf level up to root.
   * Generated by the RFC-9162 PATH algorithm (§2.1.3.2).
   */
  auditPath: Uint8Array[];
  /** Total number of leaves in the tree. */
  treeSize: number;
  /** Merkle root of the entire tree. */
  root: Uint8Array;
}

/**
 * Generate an inclusion proof for the leaf at `leafIndex` within `leaves`.
 *
 * @throws {RangeError} if `leaves` is empty or `leafIndex` is out of bounds.
 */
export function proveInclusion(
  leaves: Uint8Array[],
  leafIndex: number,
): InclusionProof {
  if (leaves.length === 0) {
    throw new RangeError('Cannot prove inclusion in an empty tree');
  }
  if (leafIndex < 0 || leafIndex >= leaves.length) {
    throw new RangeError(
      `leafIndex ${leafIndex} is out of bounds [0, ${leaves.length})`,
    );
  }
  return {
    leafIndex,
    leafHash: leaves[leafIndex],
    auditPath: buildAuditPath(leaves, leafIndex),
    treeSize: leaves.length,
    root: merkleRootFromLeaves(leaves),
  };
}

/** Build the RFC-9162 audit path for the leaf at `index` within `leaves`. */
function buildAuditPath(leaves: Uint8Array[], index: number): Uint8Array[] {
  if (leaves.length === 1) {
    return [];
  }
  const k = largestPowerOf2Below(leaves.length);
  if (index < k) {
    const rightRoot = merkleRootFromLeaves(leaves.slice(k));
    return [...buildAuditPath(leaves.slice(0, k), index), rightRoot];
  } else {
    const leftRoot = merkleRootFromLeaves(leaves.slice(0, k));
    return [...buildAuditPath(leaves.slice(k), index - k), leftRoot];
  }
}

/**
 * Verify a Merkle inclusion proof.
 *
 * Reconstructs the root by walking the RFC-9162 audit path and compares
 * the result against `proof.root`.
 *
 * Returns `false` for any malformed or inconsistent proof.
 */
export function verifyInclusionProof(proof: InclusionProof): boolean {
  if (
    proof.treeSize === 0 ||
    proof.leafIndex < 0 ||
    proof.leafIndex >= proof.treeSize
  ) {
    return false;
  }

  // RFC-9162 §2.1.4 bit-manipulation verification.
  // fn = index of the last node (tree_size - 1); fr = leaf index.
  // At each step:
  //   • If fr is ODD or fr == fn: the path entry is a LEFT sibling.
  //   • Otherwise:               the path entry is a RIGHT sibling.
  // After combining, right-shift both by 1. If we used the fr==fn branch,
  // also normalise by right-shifting while fn > 0 and fn is even (this
  // absorbs "right-heavy" subtree padding).
  let fn = proof.treeSize - 1;
  let fr = proof.leafIndex;
  let current = proof.leafHash;

  for (const p of proof.auditPath) {
    if (fn === 0) {
      return false; // audit path is longer than the tree can support
    }

    if ((fr & 1) === 1 || fr === fn) {
      // p is the LEFT sibling of the current subtree root
      current = merkleInternalHash(p, current);
      // Normalise: skip over even (left-aligned) levels using fr (not fn)
      while (fr !== 0 && (fr & 1) === 0) {
        fr >>>= 1;
        fn >>>= 1;
      }
    } else {
      // p is the RIGHT sibling of the current subtree root
      current = merkleInternalHash(current, p);
    }

    fr >>>= 1;
    fn >>>= 1;
  }

  return fn === 0 && bytesEqual(current, proof.root);
}

// ── Exclusion proof ───────────────────────────────────────────────────────────

/**
 * An exclusion proof showing that (memberId, opId) does not appear in the
 * batch window [fromSeq, toSeq].
 *
 * This is a "sorted-leaf scan certificate": the proof contains every record
 * for `memberId` in the range, each with a valid Merkle inclusion proof.
 * A verifier confirms that:
 *   1. Each included record is genuinely in the batch tree.
 *   2. None of those records has `opId == proof.opId`.
 *
 * **Note:** This construction relies on the prover honestly including all
 * records for `memberId`.  Dispute-window enforcement is an out-of-band
 * obligation of the protocol.
 */
export interface ExclusionProof {
  memberId: Uint8Array;
  opId: string;
  fromSeq: bigint;
  toSeq: bigint;
  /** Merkle root covering the full batch [fromSeq, toSeq]. */
  root: Uint8Array;
  /** Total number of leaves in the batch tree. */
  treeSize: number;
  /**
   * All records for `memberId` in the batch, each with a valid inclusion
   * proof.  May be empty when no records exist for this member.
   */
  memberRecords: Array<{
    /** Canonical CBOR encoding of the record (used to recompute leafHash). */
    encodedRecord: Uint8Array;
    /** Merkle inclusion proof for this record. */
    inclusionProof: InclusionProof;
  }>;
}

/**
 * Verify a Merkle exclusion proof.
 *
 * This verifier is stateless — it requires no access to the metering log.
 * It uses only the proof itself and recomputes everything from raw bytes.
 *
 * Returns `true` if and only if:
 *   - `BLAKE3(0x00 || encodedRecord)` matches each record's `leafHash`.
 *   - Every inclusion proof validates against `proof.root`.
 *   - Every decoded record's `memberId` matches `proof.memberId`.
 *   - No decoded record has `opId == proof.opId`.
 */
export function verifyExclusionProof(proof: ExclusionProof): boolean {
  for (const { encodedRecord, inclusionProof } of proof.memberRecords) {
    // Leaf hash must match the canonical computation.
    const expectedLeafHash = merkleLeafHash(encodedRecord);
    if (!bytesEqual(expectedLeafHash, inclusionProof.leafHash)) {
      return false;
    }

    // Inclusion proof must reference this batch's root.
    if (!bytesEqual(inclusionProof.root, proof.root)) {
      return false;
    }

    // Inclusion proof must be structurally valid.
    if (!verifyInclusionProof(inclusionProof)) {
      return false;
    }

    // Decode and validate memberId / opId.
    let record;
    try {
      record = decodeMeteringRecord(encodedRecord);
    } catch {
      return false; // Undecodable record → invalid proof
    }

    if (!bytesEqual(record.memberId, proof.memberId)) {
      return false;
    }

    if (record.opId === proof.opId) {
      return false; // opId IS present in the batch — exclusion fails
    }
  }

  return true;
}

// ── Internal utilities ────────────────────────────────────────────────────────

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}
