/**
 * Property-Based Tests for MembershipProofService
 *
 * P9: Membership Proof Content Binding
 * For any membership proof P generated for content hash H1,
 * verifyProof(P, memberKeys, H2) returns false when H1 ≠ H2.
 * The proof is bound to the specific content.
 *
 * P10: Membership Proof Non-Identifiability
 * For any membership proof P generated by member X from member set M,
 * the proof verifies against the full set M but does not reveal which
 * member generated it. (Verified by checking that verification succeeds
 * with the full key set but the proof contains no member-specific identifiers.)
 *
 * **Validates: Requirements 18.1, 18.2, 18.5**
 */
import * as fc from 'fast-check';
import * as secp256k1 from 'secp256k1';

import { MembershipProofService } from './membershipProofService';

// Set a longer timeout for property-based tests
jest.setTimeout(120000);

/**
 * Generate a valid secp256k1 key pair for testing.
 */
function generateKeyPair(): { privateKey: Uint8Array; publicKey: Uint8Array } {
  let privateKey: Uint8Array;
  do {
    privateKey = new Uint8Array(32);
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require('crypto').randomFillSync(privateKey);
  } while (!secp256k1.privateKeyVerify(privateKey));

  const publicKey = secp256k1.publicKeyCreate(privateKey, true);
  return { privateKey, publicKey };
}

/** Pre-generate a pool of key pairs (key generation is expensive) */
const keyPairPool: { privateKey: Uint8Array; publicKey: Uint8Array }[] = [];
for (let i = 0; i < 8; i++) {
  keyPairPool.push(generateKeyPair());
}

describe('MembershipProofService Property-Based Tests', () => {
  let service: MembershipProofService;

  beforeAll(() => {
    service = new MembershipProofService();
  });

  /**
   * **Validates: Requirements 18.5**
   *
   * P9: Membership Proof Content Binding
   * For any membership proof P generated for content hash H1,
   * verifyProof(P, memberKeys, H2) returns false when H1 ≠ H2.
   */
  describe('P9: Membership Proof Content Binding', () => {
    it('proof for content H1 fails verification against different content H2', async () => {
      await fc.assert(
        fc.asyncProperty(
          // Pick ring size between 1 and 6 (from our pool of 8)
          fc.integer({ min: 1, max: 6 }),
          // Pick signer index within the ring
          fc.integer({ min: 0, max: 5 }),
          // Generate two distinct content hashes (32 bytes each)
          fc.uint8Array({ minLength: 32, maxLength: 32 }),
          fc.uint8Array({ minLength: 32, maxLength: 32 }),
          async (ringSize, rawSignerIdx, h1, h2) => {
            // Ensure signer index is within ring
            const signerIdx = rawSignerIdx % ringSize;

            // Select keys from pool
            const memberKeys = keyPairPool
              .slice(0, ringSize)
              .map((kp) => kp.publicKey);
            const signerPrivateKey = keyPairPool[signerIdx].privateKey;

            // Skip if H1 === H2 (we need distinct hashes)
            if (h1.every((b, i) => b === h2[i])) {
              return; // trivially true, skip
            }

            // Generate proof bound to H1
            const proof = await service.generateProof(
              signerPrivateKey,
              memberKeys,
              h1,
            );

            // Verify against H1 should succeed
            const validResult = await service.verifyProof(
              proof,
              memberKeys,
              h1,
            );
            expect(validResult).toBe(true);

            // Verify against H2 should fail (content binding)
            const invalidResult = await service.verifyProof(
              proof,
              memberKeys,
              h2,
            );
            expect(invalidResult).toBe(false);
          },
        ),
        { numRuns: 20 },
      );
    });
  });

  /**
   * **Validates: Requirements 18.1, 18.2**
   *
   * P10: Membership Proof Non-Identifiability
   * For any membership proof P generated by member X from member set M,
   * the proof verifies against the full set M but does not reveal which
   * member generated it.
   *
   * Verified by:
   * 1. Proof verifies against the full key set
   * 2. The serialized proof bytes do not contain any member's compressed
   *    public key as a contiguous subsequence
   * 3. Different signers in the same ring produce proofs that all verify
   *    (no signer-specific verification path)
   */
  describe('P10: Membership Proof Non-Identifiability', () => {
    it('proof verifies against full set and contains no member-specific identifiers', async () => {
      await fc.assert(
        fc.asyncProperty(
          // Pick ring size between 2 and 6
          fc.integer({ min: 2, max: 6 }),
          // Generate content hash
          fc.uint8Array({ minLength: 32, maxLength: 32 }),
          async (ringSize, contentHash) => {
            const memberKeys = keyPairPool
              .slice(0, ringSize)
              .map((kp) => kp.publicKey);

            // Generate proofs from two different signers
            const signer0 = 0;
            const signer1 = 1;

            const proof0 = await service.generateProof(
              keyPairPool[signer0].privateKey,
              memberKeys,
              contentHash,
            );

            const proof1 = await service.generateProof(
              keyPairPool[signer1].privateKey,
              memberKeys,
              contentHash,
            );

            // Both proofs should verify against the full key set
            const valid0 = await service.verifyProof(
              proof0,
              memberKeys,
              contentHash,
            );
            const valid1 = await service.verifyProof(
              proof1,
              memberKeys,
              contentHash,
            );
            expect(valid0).toBe(true);
            expect(valid1).toBe(true);

            // Check that no member's compressed public key appears as a
            // contiguous subsequence in the proof bytes.
            // This verifies the proof does not leak member-specific identifiers.
            for (const pubKey of memberKeys) {
              const compressed = secp256k1.publicKeyConvert(pubKey, true);
              const proofHex = Buffer.from(proof0).toString('hex');
              const keyHex = Buffer.from(compressed).toString('hex');
              expect(proofHex).not.toContain(keyHex);
            }
          },
        ),
        { numRuns: 15 },
      );
    });
  });
});
