/**
 * @fileoverview Property-based test for default UUID generator.
 *
 * **Feature: db-core-to-lib, Property 2: Default UUID generator produces valid UUID v4**
 *
 * For any number of invocations of the default UuidGenerator (created by
 * createDefaultUuidGenerator), every returned string should match the UUID v4
 * format: xxxxxxxx-xxxx-4xxx-[89ab]xxx-xxxxxxxxxxxx.
 *
 * **Validates: Requirements 7.3, 7.4**
 */

import fc from 'fast-check';
import { createDefaultUuidGenerator } from '../uuidGenerator';

const UUID_V4_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

describe('Feature: db-core-to-lib, Property 2: Default UUID generator produces valid UUID v4', () => {
  /**
   * **Validates: Requirements 7.3, 7.4**
   *
   * For each generated invocation count, create a default UUID generator and
   * call it that many times. Every UUID produced must match the v4 format.
   */
  it('every UUID from createDefaultUuidGenerator matches UUID v4 format', () => {
    const gen = createDefaultUuidGenerator();

    fc.assert(
      fc.property(fc.integer({ min: 1, max: 10 }), (count) => {
        for (let i = 0; i < count; i++) {
          const uuid = gen();
          expect(uuid).toMatch(UUID_V4_REGEX);
        }
      }),
      { numRuns: 100 },
    );
  });
});

/**
 * **Feature: db-core-to-lib, Property 1: Custom UUID generator injection**
 *
 * For any UuidGenerator function provided to InMemoryDatabase, all IDs
 * generated by that component (session IDs, document _id values) should be
 * produced by calling the injected generator, not by any other source.
 *
 * **Validates: Requirements 2.4, 3.2, 5.2**
 */

import { BlockSize } from '../../enumerations/blockSize';
import type { BsonDocument } from '../../interfaces/storage/documentTypes';
import { MemoryBlockStore } from '../../stores/memoryBlockStore';
import { InMemoryDatabase } from '../inMemoryDatabase';
import type { UuidGenerator } from '../uuidGenerator';

describe('Feature: db-core-to-lib, Property 1: Custom UUID generator injection', () => {
  /**
   * **Validates: Requirements 2.4, 3.2, 5.2**
   *
   * For each generated operation count, create an InMemoryDatabase with a
   * custom UUID generator that produces trackable UUIDs. Verify that all
   * session IDs and document _id values come from the injected generator.
   */
  it('all generated IDs come from the injected UUID generator', async () => {
    await fc.assert(
      fc.asyncProperty(
        // Number of sessions to start
        fc.integer({ min: 1, max: 5 }),
        // Number of documents to insert per collection
        fc.integer({ min: 1, max: 5 }),
        async (sessionCount, docCount) => {
          // Track every UUID produced by our custom generator
          const generatedUuids: string[] = [];
          let callIndex = 0;

          const customGenerator: UuidGenerator = () => {
            const uuid = `custom-${String(callIndex).padStart(8, '0')}`;
            callIndex++;
            generatedUuids.push(uuid);
            return uuid;
          };

          const store = new MemoryBlockStore(BlockSize.Small);
          const db = new InMemoryDatabase(store, {
            name: 'test-db',
            uuidGenerator: customGenerator,
          });
          await db.connect();

          // 1. Verify startSession() uses the injected generator for session IDs
          const sessionIds: string[] = [];
          for (let i = 0; i < sessionCount; i++) {
            const session = db.startSession();
            sessionIds.push(session.id);
          }

          // Every session ID must be present in the generated UUIDs
          for (const sid of sessionIds) {
            expect(generatedUuids).toContain(sid);
          }

          // 2. Verify collection().insertOne() uses the injected generator for _id
          const coll = db.collection<BsonDocument>('test-coll');
          const insertedIds: string[] = [];
          for (let i = 0; i < docCount; i++) {
            const result = await coll.insertOne({
              value: i,
            } as BsonDocument);
            insertedIds.push(result.insertedId);
          }

          // Every inserted _id must be derived from the custom generator.
          // The Collection strips dashes from the UUID, so we check that
          // each insertedId matches a generated UUID with dashes removed.
          const generatedWithoutDashes = generatedUuids.map((u) =>
            u.replace(/-/g, ''),
          );
          for (const docId of insertedIds) {
            expect(generatedWithoutDashes).toContain(docId);
          }

          await db.disconnect();
        },
      ),
      { numRuns: 100 },
    );
  });
});
