export enum AuditAction {
  VAULT_CREATED = 'VAULT_CREATED',
  VAULT_OPENED = 'VAULT_OPENED',
  VAULT_DELETED = 'VAULT_DELETED',
  VAULT_SHARED = 'VAULT_SHARED',
  VAULT_SHARE_REVOKED = 'VAULT_SHARE_REVOKED',
  VAULT_UPDATED = 'VAULT_UPDATED',
  VAULT_SEED_REGENERATED = 'VAULT_SEED_REGENERATED',
  ENTRY_CREATED = 'ENTRY_CREATED',
  ENTRY_READ = 'ENTRY_READ',
  ENTRY_UPDATED = 'ENTRY_UPDATED',
  ENTRY_DELETED = 'ENTRY_DELETED',
  EMERGENCY_CONFIGURED = 'EMERGENCY_CONFIGURED',
  EMERGENCY_RECOVERED = 'EMERGENCY_RECOVERED',
  QUORUM_CONFIGURED = 'QUORUM_CONFIGURED',
}

export interface AuditLogEntry {
  id: string;
  vaultId: string;
  memberId: string;
  action: AuditAction;
  timestamp: Date;
  metadata?: Record<string, string>;
}
