import { ValidatedBody } from '@digitaldefiance/node-express-suite';
import { IRequestUserDTO } from '@digitaldefiance/suite-core-lib';
import { ValidationChain } from 'express-validator';
declare module 'express-serve-static-core' {
  interface Request {
    validatedBody?: ValidatedBody<string>;
    validate?: {
      body: (field: string) => ValidationChain;
      param: (field: string) => ValidationChain;
      query: (field: string) => ValidationChain;
      header: (field: string) => ValidationChain;
      cookie: (field: string) => ValidationChain;
    };
    /**
     * Unique request ID (UUID v4) generated by requestIdMiddleware.
     * Used for request tracing and included in error responses.
     * @requirements 9.5
     */
    requestId?: string;
  }
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Express {
    interface Request {
      user?: IRequestUserDTO;
      validatedBody?: ValidatedBody<string>;
      validate?: {
        body: (field: string) => ValidationChain;
        param: (field: string) => ValidationChain;
        query: (field: string) => ValidationChain;
        header: (field: string) => ValidationChain;
        cookie: (field: string) => ValidationChain;
      };
      /**
       * Unique request ID (UUID v4) generated by requestIdMiddleware.
       * Used for request tracing and included in error responses.
       * @requirements 9.5
       */
      requestId?: string;
    }
  }
}

export {};
